### ISSUE TITLE
Hacktoberfest 2023 🎉 : Enhance "Meet The Team" section

### ISSUE THREAD

**Issue by joeyouss** [Codess-Cafe/Codess-Website#2] opened 2023-10-14 14:43 UTC
Wait till #4 gets completed

Issue Description:
We currently have a 'Meet the Team' section on our website displaying team members' information.

[1] Change the shape of photographs in the cards from square to circle
[2] Add a button below description that would take the user to the LinkedIn page of respective team member.

Links to LinkedIn profiles:

Aarnav Jindal - https://www.linkedin.com/in/aarnavjindal/
Shriya Chabbra -  https://www.linkedin.com/in/shriya-chhabra/
Vidhi Bhatt - https://www.linkedin.com/in/vidhibhatt01/
Jyoti Bisht - https://www.linkedin.com/in/jyoti-bisht-9299181b1/
Bhumi Malla - https://www.linkedin.com/in/bhumi-malla-407153171/
Sumee Adhikari - https://www.linkedin.com/in/sumee-adhikari-28b550166/
Kulsum Siddique - https://www.linkedin.com/in/kulsum-siddique-24750379/
Hira Farooq - https://www.linkedin.com/in/hira-farooq01/
Nitya Mittal - https://www.linkedin.com/in/mittalnitya/
Subhanshi Rawat - https://www.linkedin.com/in/subhanshi-rawat/
Yashaswini Shivathaya - https://www.linkedin.com/in/yashaswini-shivathaya/

This enhancement would enhance the overall interactivity and engagement of our website, providing visitors with a seamless way to learn more about our team members.

**Comment by Surajit0573** [comment] 2023-10-15 14:37
@VidhiBhatt01 I am already working on it. Please assign me. 
I will PR after #4 is done.

**Comment by Tooba-Amjad** [comment] 2023-10-15 18:22
Already Added !
Should I CReate the pull request or not?

![Screenshot (193)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/4c786c15-4113-45ad-beb5-922555f9c677)

**Comment by VidhiBhatt01** [comment] 2023-10-15 18:32
No

**Comment by VidhiBhatt01** [comment] 2023-10-15 18:33
The whole code for placeholders would be changed most probably so wait till it gets completely resolved

**Comment by Tooba-Amjad** [comment] 2023-10-15 18:37
Ok

**Comment by VidhiBhatt01** [comment] 2023-10-16 03:56
@Tooba-Amjad, this issue is assigned to @Surajit0573. You need not work on it.

**Comment by Tooba-Amjad** [comment] 2023-10-16 05:13
Alright

**Comment by VidhiBhatt01** [comment] 2023-10-17 17:44
@Tooba-Amjad you may raise a PR for this too. Will consider whosoever out of you two raises a valid PR first (make sure it completely resolves the issue)

**Comment by Tooba-Amjad** [comment] 2023-10-17 17:51
Alright 
I'll

**Comment by Tooba-Amjad** [comment] 2023-10-18 16:42
@VidhiBhatt01 
Have a look ?
Which Linkedin symbol is best ? 
And something you want to modify?

![Screenshot (197)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/47de6f04-0f32-4586-ad63-72ab6ec1481b)

**Comment by Tooba-Amjad** [comment] 2023-10-18 18:25
@VidhiBhatt01 
Have a look 
Which Linkedin button is best?
![Screenshot (197)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/078e2626-8f62-426c-8de5-1cb57694e03c)

**Comment by Tooba-Amjad** [comment] 2023-10-18 18:26
Also the linkedin url of **Riya Dev Varshney** is missing

**Comment by VidhiBhatt01** [comment] 2023-10-18 18:32
> @VidhiBhatt01 Have a look Which Linkedin button is best? ![Screenshot (197)](https://user-images.githubusercontent.com/106931048/276361414-078e2626-8f62-426c-8de5-1cb57694e03c.png)

None honestly, try to match it with the existing UI

**Comment by VidhiBhatt01** [comment] 2023-10-18 18:33
> Also the linkedin url of **Riya Dev Varshney** is missing

We are updating the details in #4

**Comment by Tooba-Amjad** [comment] 2023-10-18 18:51
Have a look

![Screenshot (199)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/dd92e491-918f-411d-8a42-645f9f1f19a7)

**Comment by VidhiBhatt01** [comment] 2023-10-18 18:54
Use the logo used in socials bar

**Comment by Tooba-Amjad** [comment] 2023-10-18 19:27
**Option 1**
![Screenshot (200)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/118cd263-c6d2-4748-b1f5-93df624443b4)
**Option 2**
![Screenshot (202)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/b3f32eff-1f70-43a0-b91a-db93da2e8301)
**Option 3**
![Screenshot (203)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/c4fc8f12-aa30-490f-80a0-339cef7fee5a)
**Option 4**
![Screenshot (201)](https://github.com/Codess-Cafe/Codess-Website/assets/106931048/3600a693-8d95-4f14-80d5-9faf2ef8249f)

**Comment by Tooba-Amjad** [comment] 2023-10-20 01:37
@VidhiBhatt01 @devaar100 @Ruchip16 Have a look  and tell me which option is best

**Comment by VidhiBhatt01** [comment] 2023-10-20 04:43
![image](https://github.com/Codess-Cafe/Codess-Website/assets/83345228/311a0717-9a18-44f1-a414-ed5a5feb01c9)


Lower the photo in the placeholder a little and add logo on right hand corner

**Comment by VidhiBhatt01** [comment] 2023-10-20 04:46
@Tooba-Amjad can you  directly raise a PR for resolving #4 first? The current contributor is making multiple mistakes and the issue is taking longer than usual to complete.. I will assign it to you later

**Comment by Tooba-Amjad** [comment] 2023-10-20 04:49
Yes sure

**Comment by VidhiBhatt01** [comment] 2023-10-21 10:02
@Tooba-Amjad, #4 is fixed. Pull the latest changes and raise PR for #2..

**Comment by Tooba-Amjad** [comment] 2023-10-21 10:13
Alright

**Closed** 2023-10-29 14:24 UTC
Labels: good first issue, hacktoberfest
